### ISSUE TITLE
Support deployment and automatic redeploy to OpenShift for SpringBoot based Fuse application

### ISSUE THREAD

**Issue by apupier** [camel-tooling/vscode-camel-extension-pack#15]
- [ ] Have Fuse images listed in component types
  - [ ] Remove "hidden" tag in minishift addon https://github.com/minishift/minishift/issues/3193 https://github.com/minishift/minishift/pull/3194
  - [x] Remove "hidden" tag in openshift ansible for OpenShift 3.10 https://github.com/openshift/openshift-ansible/issues/11292 https://github.com/openshift/openshift-ansible/pull/11294
  - [ ] Remove "hidden" tag in openshift ansible for OpenShift 3.11 https://github.com/openshift/openshift-ansible/issues/11292 https://github.com/openshift/openshift-ansible/pull/11293
  - [ ] Remove "hidden" tag in jboss-fuse image streams https://github.com/jboss-fuse/application-templates/issues/56 https://github.com/jboss-fuse/application-templates/pull/57
- [ ] First push of long-running build fails to start the Java program in the pod (which is the case for Fuse applications) https://github.com/redhat-developer/odo/issues/1430
- [ ] Odo watch is rebuilding the initial version, ignoring pushed modifications https://github.com/redhat-developer/odo/issues/1429
- [ ] Include Fuse SpringBoot-based image in odo test suite https://github.com/redhat-developer/odo/issues/1428

**Comment by lhein** [comment]
closing as stale
